language: node_js
addons:
  ssh_known_hosts: 163.172.151.151
node_js: node
install: npm install
before_deploy:
  - openssl aes-256-cbc -K $encrypted_a38144795215_key -iv $encrypted_a38144795215_iv -in deployment_key.pem.enc -out /tmp/deployment_key.pem -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deployment_key.pem
  - ssh-add /tmp/deployment_key.pem
  - rm -f /tmp/deployment_key.pem
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR node_user@163.172.151.151
  on:
    branch: master
